apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "bankflow-service.labels" . | nindent 4 }}
data:
  {{- with .Values.database.url }}
  SPRING_DATASOURCE_URL: {{ . | quote }}
  {{- end }}
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}